# fly.toml app configuration file generated for astrology-ui on 2025-05-27T15:53:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'astrology-ui'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
