"""add deleted column to horoscopes

Revision ID: 353d5f62d7b2
Revises: 77804ca18b32
Create Date: 2025-05-31 17:49:31.453388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353d5f62d7b2'
down_revision: Union[str, None] = '77804ca18b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscopes', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # op.alter_column('horoscopes', 'chart_image',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    op.create_index(op.f('ix_matchmaking_results_id'), 'matchmaking_results', ['id'], unique=False)
    op.alter_column('places', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('places', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('places', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('places', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('places', 'timezone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('places', 'created_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('places', 'updated_at',
               existing_type=sa.NUMERIC(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.alter_column('places', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('places', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('places', 'timezone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('places', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('places', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('places', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('places', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_matchmaking_results_id'), table_name='matchmaking_results')
    # op.alter_column('horoscopes', 'chart_image',
    #            existing_type=sa.String(length=255),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    op.drop_column('horoscopes', 'deleted')
    # ### end Alembic commands ###
